### PR TITLE
Blocking creeps

### PR DESCRIPTION
**Pull request by saarikoski-jules**
- User can now block users from user settings screens. Messages from blocked users will not be delivered and blocked user will be warned

### CODE REVIEW

**Comment by VictorTennekes** [comment]
Small edge case with blocking described in #30. Do we wanna add a list/input field to unban players as well?

Overall it looks great!

**Comment by Tishj** [comment]
It works, I dont necessarily agree with the location in the app for blocking, but the functionality can always be moved :)

**Comment by saarikoski-jules** [comment]
fix #30 in thijs' commit f4f4580

**Review by VictorTennekes — APPROVED** [review]
Nice work! Functionality is great!

**Pull request merged**
