### PR TITLE
You can now generate multi-user chats

### PR DESCRIPTION
**Pull request by saarikoski-jules**
- Added chat to slot in the main page
- Added a generate page where you can create a new chat and add users to it
- Added password protected chats
- Protected private and password protected chats from unauthorized users
- Moved all chat components to chat directory

### CODE REVIEW

**Comment by Tishj** [comment]
Bug: Password protected chat does not update messages in realtime

Steps to reproduce:
Create a password protected chat, join it, send a message

Expected result:
New message is displayed automatically

Actual result:
New message only shows up on re-entering of the chat

**Comment by saarikoski-jules** [comment]
> Bug: chat socket sometimes stops working
> 
> EDIT: (cant reproduce :/)
> Steps to reproduce:
> Send a message in a chat
> 
> Expected result:
> New message is displayed automatically
> 
> Actual result:
> New message only shows up on re-entering of the chat

Fixed in commit 3b31d58

**Comment by VictorTennekes** [comment]
Overall looking really good, the chat seems to have some issues with longer messages resulting in the message box expanding and covering the main part of the website. Is probably fixable with text wrapping.

I have tried the following tutorial: https://newbedev.com/angular-material-5-show-full-text-in-mat-lists-word-wrap

which doesn't seem to work for me at least but will keep looking I can find something that works!

**Review by VictorTennekes — APPROVED** [review]
Good stuff! 👍

**Pull request merged**
